[project]
name = "youtube-dl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=5.2.2",
    "imageio-ffmpeg>=0.6.0",
    "pyinstaller>=6.16.0",
    "yt-dlp>=2025.11.12",
]
